sonar.projectKey=cicd-tasklist-backend
sonar.projectName=cicd-tasklist-backend
sonar.sources=src
sonar.tests=src/__tests__
sonar.exclusions=node_modules/**,dist/**,coverage/**,coverage-*/**,reports/**
sonar.javascript.lcov.reportPaths=coverage-unit/lcov.info,coverage-e2e/lcov.info
sonar.sourceEncoding=UTF-8
